import '@testing-library/jest-dom/vitest'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { apiClient } from '../../../shared/lib/api-client'
import OptionGroupsPage from './option-groups-page'

vi.mock('../../../shared/lib/api-client', () => ({ apiClient: { get: vi.fn(), post: vi.fn(), patch: vi.fn(), delete: vi.fn() } }))
const mockedApi = vi.mocked(apiClient)
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); render(<QueryClientProvider client={client}><OptionGroupsPage /></QueryClientProvider>) }
const groups = [{ id: 'g1', name: 'Size', isRequired: true, minSelect: 1, maxSelect: 1, sortOrder: 10, options: [{ id: 'o1', label: 'S', priceDeltaVnd: 0, isDefault: true, sortOrder: 10 }, { id: 'o2', label: 'L', priceDeltaVnd: 5000, isDefault: false, sortOrder: 20 }] }, { id: 'g2', name: 'Topping', isRequired: false, minSelect: 0, maxSelect: 3, sortOrder: 20, options: [] }]

describe('OptionGroupsPage', () => {
  beforeEach(() => { vi.resetAllMocks(); window.dispatchEvent = vi.fn() })
  it('renders loading, list, badges and option counts', async () => { mockedApi.get.mockResolvedValue({ data: groups }); renderPage(); expect(screen.getAllByLabelText('Đang tải dữ liệu').length).toBeGreaterThan(0); expect(await screen.findByText('Size')).toBeInTheDocument(); expect(screen.getByText('Bắt buộc')).toBeInTheDocument(); expect(screen.getByText('Không bắt buộc')).toBeInTheDocument(); expect(screen.getByText('1-1')).toBeInTheDocument(); expect(screen.getByText('2')).toBeInTheDocument() })
  it('renders safe error retry and empty state', async () => { mockedApi.get.mockRejectedValueOnce(new Error('ECONNRESET')); renderPage(); expect(await screen.findByText('Không tải được nhóm tùy chọn')).toBeInTheDocument(); expect(screen.queryByText('ECONNRESET')).not.toBeInTheDocument(); mockedApi.get.mockResolvedValueOnce({ data: [] }); await userEvent.click(screen.getByRole('button', { name: 'Thử lại' })); expect(await screen.findByText('Chưa có nhóm tùy chọn nào. Tạo nhóm đầu tiên để bắt đầu.')).toBeInTheDocument() })
  it('validates and creates with default option payload', async () => { mockedApi.get.mockResolvedValue({ data: groups }); mockedApi.post.mockResolvedValue({ data: groups[0] }); renderPage(); await screen.findByText('Size'); await userEvent.click(screen.getByRole('button', { name: '+ Tạo nhóm tùy chọn' })); await userEvent.click(screen.getByRole('button', { name: 'Tạo nhóm tùy chọn' })); expect(await screen.findAllByText('Vui lòng nhập tên nhóm')).not.toHaveLength(0); await userEvent.type(screen.getByLabelText('Tên nhóm'), 'Milk'); await userEvent.type(screen.getByLabelText('Tên tùy chọn'), 'Sữa tươi'); await userEvent.click(screen.getByRole('button', { name: 'Tạo nhóm tùy chọn' })); await waitFor(() => expect(mockedApi.post).toHaveBeenCalledWith('/option-groups', { name: 'Milk', isRequired: false, minSelect: 0, maxSelect: 1, sortOrder: 30, options: [{ label: 'Sữa tươi', priceDeltaVnd: 0, isDefault: false, sortOrder: 10 }] })) })
  it('prefills edit and patches full options with ids', async () => { mockedApi.get.mockResolvedValue({ data: groups }); mockedApi.patch.mockResolvedValue({ data: groups[0] }); renderPage(); await screen.findByText('Size'); await userEvent.click(screen.getAllByRole('button', { name: 'Sửa' })[0]); expect(screen.getByLabelText('Tên nhóm')).toHaveValue('Size'); expect(screen.getByDisplayValue('L')).toBeInTheDocument(); await userEvent.clear(screen.getByLabelText('Tên nhóm')); await userEvent.type(screen.getByLabelText('Tên nhóm'), 'Size mới'); await userEvent.click(screen.getByRole('button', { name: 'Lưu thay đổi' })); await waitFor(() => expect(mockedApi.patch).toHaveBeenCalledWith('/option-groups/g1', expect.objectContaining({ name: 'Size mới', options: expect.arrayContaining([expect.objectContaining({ id: 'o1', label: 'S' }), expect.objectContaining({ id: 'o2', label: 'L' })]) }))) })
  it('adds/removes inline options without API before submit and previews negative VND', async () => { mockedApi.get.mockResolvedValue({ data: groups }); renderPage(); await screen.findByText('Size'); await userEvent.click(screen.getByRole('button', { name: '+ Tạo nhóm tùy chọn' })); await userEvent.type(screen.getByLabelText('Tên nhóm'), 'Discount'); await userEvent.type(screen.getByLabelText('Tên tùy chọn'), 'Nhỏ'); await userEvent.clear(screen.getByLabelText('Delta giá')); await userEvent.type(screen.getByLabelText('Delta giá'), '-5000'); expect(screen.getByText(/-5.000/)).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: '+ Thêm tùy chọn' })); expect(mockedApi.post).not.toHaveBeenCalled(); await userEvent.type(screen.getAllByLabelText('Tên tùy chọn')[1], 'Lớn'); await userEvent.click(screen.getByLabelText('Xóa tùy chọn Lớn')); expect(screen.queryByDisplayValue('Lớn')).not.toBeInTheDocument() })
  it('validates multiple defaults for single select', async () => { mockedApi.get.mockResolvedValue({ data: groups }); renderPage(); await screen.findByText('Size'); await userEvent.click(screen.getAllByRole('button', { name: 'Sửa' })[0]); await userEvent.click(screen.getAllByText('Mặc định')[1]); await userEvent.click(screen.getByRole('button', { name: 'Lưu thay đổi' })); expect(await screen.findByText('Nhóm chọn một chỉ được có tối đa 1 tùy chọn mặc định')).toBeInTheDocument(); expect(mockedApi.patch).not.toHaveBeenCalled() })
  it('deletes success and maps 409 in-use count while keeping dialog open', async () => { mockedApi.get.mockResolvedValue({ data: groups }); mockedApi.delete.mockRejectedValueOnce({ response: { status: 409, data: { detail: 'Có 3 sản phẩm đang gán' } } }).mockResolvedValueOnce({}); renderPage(); await screen.findByText('Size'); await userEvent.click(screen.getAllByRole('button', { name: 'Xóa' })[0]); expect(screen.getByText('Không thể hoàn tác. Nếu nhóm đang gán cho sản phẩm, hệ thống sẽ chặn xóa.')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Xóa' })); await waitFor(() => expect(window.dispatchEvent).toHaveBeenCalledWith(expect.objectContaining({ detail: 'Nhóm đang gán cho 3 sản phẩm. Bỏ gán nhóm tùy chọn khỏi sản phẩm trước khi xóa' }))); await userEvent.click(screen.getByRole('button', { name: 'Xóa' })); await waitFor(() => expect(mockedApi.delete).toHaveBeenCalledWith('/option-groups/g1')) })
})
