import '@testing-library/jest-dom/vitest'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { apiClient } from '../../../shared/lib/api-client'
import AreasPage from './areas-page'

vi.mock('../../../shared/lib/api-client', () => ({ apiClient: { get: vi.fn(), post: vi.fn(), patch: vi.fn(), delete: vi.fn() } }))
const mockedApi = vi.mocked(apiClient)
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); render(<QueryClientProvider client={client}><AreasPage /></QueryClientProvider>) }
const areas = [{ id: '11111111-1111-4111-8111-111111111111', name: 'Quầy chính', sortOrder: 10, isActive: true, createdAt: '', updatedAt: '' }, { id: '22222222-2222-4222-8222-222222222222', name: 'Sân vườn', sortOrder: 20, isActive: false, createdAt: '', updatedAt: '' }]
const tables = [{ id: 't1', areaId: areas[0]!.id, name: 'Bàn 1', capacity: 2, sortOrder: 10, isActive: true, createdAt: '', updatedAt: '' }, { id: 't2', areaId: areas[0]!.id, name: 'Bàn 2', capacity: 2, sortOrder: 20, isActive: true, createdAt: '', updatedAt: '' }]

describe('AreasPage', () => {
  beforeEach(() => { vi.resetAllMocks(); window.dispatchEvent = vi.fn() })
  it('renders loading skeleton and list columns with derived table count', async () => { mockedApi.get.mockResolvedValueOnce({ data: areas }).mockResolvedValueOnce({ data: tables }); renderPage(); expect(screen.getAllByLabelText('Đang tải dữ liệu').length).toBeGreaterThan(0); expect(await screen.findByText('Quầy chính')).toBeInTheDocument(); expect(screen.getByText('Số bàn')).toBeInTheDocument(); expect(screen.getByText('2')).toBeInTheDocument(); expect(screen.getByText('Tạm ẩn')).toBeInTheDocument() })
  it('renders safe error retry and empty onboarding CTAs', async () => { mockedApi.get.mockImplementation((url) => url === '/areas' ? Promise.reject(new Error('traceId-secret')) : Promise.resolve({ data: [] })); renderPage(); expect(await screen.findByText('Không tải được khu vực')).toBeInTheDocument(); expect(screen.queryByText('traceId-secret')).not.toBeInTheDocument(); mockedApi.get.mockResolvedValue({ data: [] }); await userEvent.click(screen.getByRole('button', { name: 'Thử lại' })); expect(await screen.findByText(/Bắt đầu quản lý bàn/)).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Tạo khu vực' })).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Tạo bàn mẫu' })).toBeInTheDocument() })
  it('validates create, maps duplicate name to field error, and creates demo tables', async () => { mockedApi.get.mockResolvedValue({ data: [] }); mockedApi.post.mockRejectedValueOnce({ response: { status: 409, data: { type: 'https://pos.example/errors/area-name-conflict' } } }).mockResolvedValueOnce({ data: areas[0] }).mockResolvedValueOnce({ data: tables[0] }).mockResolvedValueOnce({ data: tables[1] }).mockResolvedValueOnce({ data: tables[0] }).mockResolvedValueOnce({ data: tables[1] }); renderPage(); await screen.findByText(/Bắt đầu quản lý bàn/); await userEvent.click(screen.getByRole('button', { name: 'Tạo khu vực' })); await userEvent.click(screen.getByRole('button', { name: 'Tạo khu vực' })); expect(await screen.findByText('Vui lòng nhập tên khu vực')).toBeInTheDocument(); await userEvent.type(screen.getByLabelText('Tên khu vực'), 'Quầy chính'); await userEvent.click(screen.getByRole('button', { name: 'Tạo khu vực' })); expect(await screen.findByText('Tên đã tồn tại trong store')).toBeInTheDocument(); await userEvent.keyboard('{Escape}'); await userEvent.click(screen.getByRole('button', { name: 'Tạo bàn mẫu' })); await waitFor(() => expect(mockedApi.post).toHaveBeenCalledWith('/areas', { name: 'Quầy chính', sortOrder: 10, isActive: true })); await waitFor(() => expect(mockedApi.post).toHaveBeenCalledWith('/tables', expect.objectContaining({ name: 'Bàn 4', capacity: 2, sortOrder: 40 }))) })
  it('prefills edit, patches, toggles optimistically with rollback, and maps delete 409 tableCount', async () => { mockedApi.get.mockResolvedValue({ data: areas }).mockResolvedValueOnce({ data: areas }).mockResolvedValueOnce({ data: tables }); mockedApi.patch.mockRejectedValueOnce(new Error('fail')).mockResolvedValueOnce({ data: areas[0] }); mockedApi.delete.mockRejectedValueOnce({ response: { status: 409, data: { type: 'https://pos.example/errors/area-has-tables', tableCount: 3 } } }); renderPage(); await screen.findByText('Quầy chính'); await userEvent.click(screen.getByLabelText('Tắt khu vực Quầy chính')); await waitFor(() => expect(window.dispatchEvent).toHaveBeenCalledWith(expect.objectContaining({ detail: 'Không cập nhật được trạng thái. Vui lòng thử lại.' }))); await userEvent.click(screen.getAllByRole('button', { name: 'Sửa' })[0]!); expect(screen.getByLabelText('Tên khu vực')).toHaveValue('Quầy chính'); await userEvent.clear(screen.getByLabelText('Tên khu vực')); await userEvent.type(screen.getByLabelText('Tên khu vực'), 'Quầy mới'); await userEvent.click(screen.getByRole('button', { name: 'Lưu thay đổi' })); await waitFor(() => expect(mockedApi.patch).toHaveBeenCalledWith(`/areas/${areas[0]!.id}`, expect.objectContaining({ name: 'Quầy mới' }))); await userEvent.click(screen.getAllByRole('button', { name: 'Xóa' })[0]!); await userEvent.click(screen.getByRole('button', { name: 'Xóa' })); await waitFor(() => expect(window.dispatchEvent).toHaveBeenCalledWith(expect.objectContaining({ detail: 'Khu vực này có 3 bàn. Vui lòng chuyển bàn sang khu vực khác trước.' }))) })
})
