import '@testing-library/jest-dom/vitest'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter } from 'react-router-dom'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { apiClient } from '../../../shared/lib/api-client'
import TablesPage from './tables-page'

vi.mock('../../../shared/lib/api-client', () => ({ apiClient: { get: vi.fn(), post: vi.fn(), patch: vi.fn(), delete: vi.fn() } }))
const mockedApi = vi.mocked(apiClient)
const areaA = { id: '11111111-1111-4111-8111-111111111111', name: 'Quầy chính', sortOrder: 10, isActive: true, createdAt: '', updatedAt: '' }
const areaB = { id: '22222222-2222-4222-8222-222222222222', name: 'Sân vườn', sortOrder: 20, isActive: true, createdAt: '', updatedAt: '' }
const tables = [{ id: '33333333-3333-4333-8333-333333333333', areaId: areaA.id, name: 'Bàn 1', capacity: 2, sortOrder: 10, isActive: true, createdAt: '', updatedAt: '' }, { id: '44444444-4444-4444-8444-444444444444', areaId: areaB.id, name: 'Bàn 2', capacity: 4, sortOrder: 20, isActive: false, createdAt: '', updatedAt: '' }]
function renderPage(initialEntries = ['/admin/tables/tables']) { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); render(<MemoryRouter initialEntries={initialEntries}><QueryClientProvider client={client}><TablesPage /></QueryClientProvider></MemoryRouter>) }

describe('TablesPage', () => {
  beforeEach(() => { vi.resetAllMocks(); window.dispatchEvent = vi.fn() })
  it('renders loading, list columns, area lookup, and active filter', async () => { mockedApi.get.mockImplementation((url) => Promise.resolve({ data: url === '/areas' ? [areaA, areaB] : tables })); renderPage(); expect(screen.getAllByLabelText('Đang tải dữ liệu').length).toBeGreaterThan(0); expect(await screen.findByText('Bàn 1')).toBeInTheDocument(); expect(screen.getAllByText('Khu vực').length).toBeGreaterThan(0); expect(screen.getByText('Sức chứa')).toBeInTheDocument(); expect(screen.getAllByText('Quầy chính').length).toBeGreaterThan(0); await userEvent.click(screen.getByLabelText('Chỉ hiển thị đang hoạt động')); await waitFor(() => expect(screen.queryByText('Bàn 2')).not.toBeInTheDocument()) })
  it('syncs areaId URL filter and shows empty states for no tables and no areas', async () => { mockedApi.get.mockResolvedValueOnce({ data: [areaA, areaB] }).mockResolvedValueOnce({ data: tables }); renderPage(); await screen.findByText('Bàn 1'); await userEvent.selectOptions(screen.getByLabelText('Khu vực'), areaB.id); await waitFor(() => expect(screen.queryByText('Bàn 1')).not.toBeInTheDocument()); expect(screen.getByText('Bàn 2')).toBeInTheDocument(); mockedApi.get.mockReset(); mockedApi.get.mockResolvedValueOnce({ data: [] }).mockResolvedValueOnce({ data: [] }); renderPage(['/admin/tables/tables']); expect(await screen.findByText('Vui lòng tạo khu vực trước khi thêm bàn.')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Đi tới Khu vực' })).toBeInTheDocument() })
  it('validates create, maps duplicate and area validation errors, then patches edit', async () => { mockedApi.get.mockImplementation((url) => Promise.resolve({ data: url === '/areas' ? [areaA] : tables })); mockedApi.post.mockRejectedValueOnce({ response: { status: 409, data: { type: 'https://pos.example/errors/table-name-conflict' } } }).mockRejectedValueOnce({ response: { status: 400, data: { type: 'https://pos.example/errors/validation' } } }); mockedApi.patch.mockResolvedValue({ data: tables[0] }); renderPage(); await screen.findByText('Bàn 1'); await userEvent.click(screen.getByRole('button', { name: '+ Tạo bàn mới' })); await userEvent.click(screen.getByRole('button', { name: 'Tạo bàn' })); expect(await screen.findByText('Vui lòng nhập tên bàn')).toBeInTheDocument(); await userEvent.type(screen.getByLabelText('Tên bàn'), 'Bàn 1'); await userEvent.click(screen.getByRole('button', { name: 'Tạo bàn' })); expect(await screen.findByText('Tên đã tồn tại trong store')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Tạo bàn' })); expect(await screen.findByText('Khu vực không hợp lệ hoặc không thuộc store')).toBeInTheDocument(); await userEvent.keyboard('{Escape}'); await userEvent.click(screen.getAllByRole('button', { name: 'Sửa' })[0]!); expect(screen.getByLabelText('Tên bàn')).toHaveValue('Bàn 1'); await userEvent.clear(screen.getByLabelText('Tên bàn')); await userEvent.type(screen.getByLabelText('Tên bàn'), 'Bàn VIP'); await userEvent.click(screen.getByRole('button', { name: 'Lưu thay đổi' })); await waitFor(() => expect(mockedApi.patch).toHaveBeenCalledWith(`/tables/${tables[0]!.id}`, expect.objectContaining({ name: 'Bàn VIP', areaId: areaA.id }))) })
  it('toggles rollback and maps delete pending order count', async () => { mockedApi.get.mockImplementation((url) => Promise.resolve({ data: url === '/areas' ? [areaA] : tables })); mockedApi.patch.mockRejectedValueOnce(new Error('fail')); mockedApi.delete.mockRejectedValueOnce({ response: { status: 409, data: { type: 'https://pos.example/errors/table-has-pending-order', activeOrderCount: 2 } } }); renderPage(); await screen.findByText('Bàn 1'); await userEvent.click(screen.getByLabelText('Tắt bàn Bàn 1')); await waitFor(() => expect(window.dispatchEvent).toHaveBeenCalledWith(expect.objectContaining({ detail: 'Không cập nhật được trạng thái. Vui lòng thử lại.' }))); await userEvent.click(screen.getAllByRole('button', { name: 'Xóa' })[0]!); await userEvent.click(screen.getByRole('button', { name: 'Xóa' })); await waitFor(() => expect(window.dispatchEvent).toHaveBeenCalledWith(expect.objectContaining({ detail: 'Bàn này đang có 2 đơn chờ thanh toán. Vui lòng xử lý đơn trước khi xóa.' }))) })
})
