import { useMemo, useReducer, useState } from 'react'
import type { MenuOptionGroupRecord, MenuOptionRecord, MenuProductRecord } from '../../../db/schemas/menu'
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle } from '../../../shared/components/ui/dialog'
import { formatVnd } from '../../../shared/lib/format-vnd'
import { getTextInitials } from '../../../shared/lib/text-initials'
import type { CartItemInput } from '../../orders/types'
import { useOptionGroupsForProduct } from '../hooks'

type OptionGroupWithOptions = { group: MenuOptionGroupRecord; options: MenuOptionRecord[] }
type OptionModalProps = { product: MenuProductRecord | null; open: boolean; onOpenChange: (open: boolean) => void; onAddToCart: (item: CartItemInput) => void }
function initialSelections(groups: OptionGroupWithOptions[]): Record<string, string[]> { return Object.fromEntries(groups.map(({ group, options }) => [group.id, options.filter((option) => option.isDefault).slice(0, Math.max(1, group.maxSelect)).map((option) => option.id)])) }
function minimumRequiredSelections(group: MenuOptionGroupRecord): number { return Math.max(group.isRequired ? 1 : 0, group.minSelect) }
function missingGroup(groups: OptionGroupWithOptions[], selections: Record<string, string[]>): MenuOptionGroupRecord | undefined { return groups.find(({ group, options }) => { const minimum = minimumRequiredSelections(group); if (minimum <= 0) return false; if (options.length < minimum) return true; return (selections[group.id]?.length ?? 0) < minimum })?.group }
function optionLabel(option: MenuOptionRecord) { if (!option.priceDeltaVnd) return option.label; return `${option.label} (${option.priceDeltaVnd > 0 ? '+' : ''}${formatVnd(option.priceDeltaVnd)})` }

export function OptionModal({ product, open, onOpenChange, onAddToCart }: OptionModalProps) {
  const groups = useOptionGroupsForProduct(open ? product : null)
  const [overrides, setOverrides] = useState<Record<string, string[]> | null>(null)
  const [note, setNote] = useState('')
  const [feedback, setFeedback] = useState('')
  const [resetKey, resetDraft] = useReducer((value: number) => value + 1, 0)
  const defaultSelections = useMemo(() => initialSelections(groups ?? []), [groups])
  const selections = useMemo(() => overrides ?? defaultSelections, [overrides, defaultSelections])
  const selectedOptions = useMemo(() => { if (!groups) return []; const selected = new Set(Object.values(selections).flat()); return groups.flatMap(({ options }) => options.filter((option) => selected.has(option.id))) }, [groups, selections])
  const previewPrice = (product?.priceVnd ?? 0) + selectedOptions.reduce((sum, option) => sum + option.priceDeltaVnd, 0)
  const firstMissingGroup = groups ? missingGroup(groups, selections) : undefined
  const canAdd = Boolean(product && groups && groups.length > 0 && !firstMissingGroup)
  function updateOpen(openValue: boolean) { if (!openValue) { setOverrides(null); setNote(''); setFeedback(''); resetDraft() } onOpenChange(openValue) }
  function updateSelections(updater: (current: Record<string, string[]>) => Record<string, string[]>) { setOverrides((current) => updater(current ?? selections)) }
  function toggleOption(group: MenuOptionGroupRecord, option: MenuOptionRecord) { const currentIds = selections[group.id] ?? []; const isSelected = currentIds.includes(option.id); setFeedback(''); if (group.maxSelect === 1) { updateSelections((current) => ({ ...current, [group.id]: [option.id] })); return } if (isSelected) { const minimum = Math.max(group.isRequired ? 1 : 0, group.minSelect); if (currentIds.length <= minimum) return; updateSelections((current) => ({ ...current, [group.id]: currentIds.filter((id) => id !== option.id) })); return } if (currentIds.length >= group.maxSelect) { setFeedback(`Tối đa ${group.maxSelect} ${group.name.toLocaleLowerCase('vi')}`); return } updateSelections((current) => ({ ...current, [group.id]: [...currentIds, option.id] })) }
  function handleAdd() { if (!product || !groups || !canAdd) return; const selected = new Set(Object.values(selections).flat()); const options = groups.flatMap(({ options }) => options.filter((option) => selected.has(option.id))); const input: CartItemInput = { productId: product.id, productNameSnapshot: product.name, unitPriceSnapshot: product.priceVnd, options: options.map((option) => ({ optionId: option.id, labelSnapshot: option.label, priceDeltaSnapshot: option.priceDeltaVnd })), quantity: 1, lineTotal: product.priceVnd + options.reduce((sum, option) => sum + option.priceDeltaVnd, 0) }; const trimmedNote = note.trim(); if (trimmedNote) input.note = trimmedNote; onAddToCart(input); updateOpen(false) }
  return (
    <Dialog key={`${product?.id ?? 'none'}-${resetKey}`} open={open} onOpenChange={updateOpen}>
      <DialogContent className="pos-theme flex max-h-[90vh] w-[min(92vw,45rem)] flex-col overflow-hidden rounded-[28px] p-0" aria-describedby="option-modal-description">
        <header className="flex items-start justify-between gap-5 border-b border-outline-variant/35 p-6"><div className="flex gap-5"><div className="h-24 w-24 shrink-0 rounded-[20px] bg-surface-container-low overflow-hidden shadow-inner flex items-center justify-center">{product?.imageUrl ? <img src={product.imageUrl} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full w-full place-items-center bg-gradient-to-br from-primary-container/70 to-surface-container-high text-3xl font-bold text-primary/45">{getTextInitials(product?.name ?? '')}</div>}</div><div className="pt-1"><DialogTitle className="text-[28px] font-semibold leading-9 text-on-surface">{product?.name ?? 'Tùy chọn sản phẩm'}</DialogTitle><DialogDescription id="option-modal-description" className="mt-2 max-w-[28rem] font-body-md text-on-surface-variant">Tùy chỉnh size, topping và ghi chú cho đơn hiện tại.</DialogDescription></div></div><DialogClose aria-label="Đóng" className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-on-surface-variant hover:bg-surface-container focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"><span aria-hidden="true" className="material-symbols-outlined">close</span></DialogClose></header>
        <div className="flex-1 space-y-7 overflow-y-auto px-6 py-7">{!groups ? <div role="status" className="rounded-2xl border border-outline-variant/30 bg-surface-container p-4 text-sm">Đang tải tùy chọn...</div> : null}{groups?.map(({ group, options }) => { const selectedIds = selections[group.id] ?? []; const isMissing = firstMissingGroup?.id === group.id; const chipRole = group.isRequired && group.maxSelect === 1 ? 'radio' : 'checkbox'; return <section key={group.id} role="group" aria-label={group.name} className={isMissing ? 'rounded-2xl p-2 ring-2 ring-error/40' : ''}><label className="mb-3 block text-[13px] font-bold uppercase tracking-[0.16em] text-on-surface-variant">{group.name}</label><div className="grid grid-cols-2 gap-3">{options.map((option, index) => { const selected = selectedIds.includes(option.id); const lastOdd = options.length % 2 === 1 && index === options.length - 1; return <button key={option.id} type="button" role={chipRole} aria-checked={selected} onClick={() => toggleOption(group, option)} className={`${lastOdd ? 'col-span-2' : ''} min-h-[56px] rounded-2xl px-4 py-3 text-center font-body-md transition ${selected ? 'border-2 border-primary bg-primary-container font-bold text-on-primary-container shadow-sm shadow-primary/20' : 'border border-outline-variant/70 bg-surface text-on-surface hover:bg-surface-container'}`}>{optionLabel(option)}</button> })}</div>{isMissing ? <p className="mt-2 font-label-sm text-error">Chọn {group.name} để tiếp tục</p> : null}{options.length === 0 ? <p className="mt-2 text-sm text-on-surface-variant">Tùy chọn chưa sẵn sàng.</p> : null}</section> })}{feedback ? <p role="status" aria-live="polite" className="rounded-xl border border-warning/40 bg-warning/10 p-2 text-sm">{feedback}</p> : null}<section><label className="mb-2 block text-[13px] font-bold uppercase tracking-[0.16em] text-on-surface-variant" htmlFor="cart-item-note">Ghi chú</label><textarea id="cart-item-note" value={note} onChange={(event) => setNote(event.target.value)} maxLength={200} placeholder="Ghi chú (tùy chọn)" className="min-h-20 w-full rounded-2xl border border-outline-variant/70 bg-surface px-4 py-3 focus:ring-2 focus:ring-primary" /></section></div>
        <footer className="flex items-center justify-between border-t border-outline-variant/35 bg-surface px-6 py-5"><div className="flex flex-col"><span className="text-[12px] font-bold uppercase tracking-[0.16em] text-on-surface-variant">Tạm tính</span><span className="total mt-1 text-[30px] font-semibold leading-9 text-on-surface">{formatVnd(previewPrice)}</span></div><button type="button" disabled={!canAdd} onClick={handleAdd} aria-label={`Thêm vào giỏ ${formatVnd(previewPrice)}`} className="flex h-[58px] items-center gap-3 rounded-2xl bg-primary px-9 font-headline-md text-on-primary shadow-lg shadow-primary/25 hover:bg-primary-hover active:scale-95 disabled:cursor-not-allowed disabled:opacity-50"><span aria-hidden="true" className="material-symbols-outlined">shopping_cart_checkout</span>Thêm vào giỏ</button></footer>
      </DialogContent>
    </Dialog>
  )
}
