import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-muted': 'var(--color-surface-muted)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-primary': 'var(--color-on-primary)',
        accent: 'var(--color-accent)',
        success: 'var(--color-success)',
        tertiary: 'var(--color-tertiary)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        error: 'var(--color-error)',
        'error-container': 'var(--color-error-container)',
        'on-error-container': 'var(--color-on-error-container)',
        border: 'var(--color-border)',
        'outline-variant': 'var(--color-outline-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'admin-brand': { 25: 'var(--color-admin-brand-25)', 50: 'var(--color-admin-brand-50)', 100: 'var(--color-admin-brand-100)', 200: 'var(--color-admin-brand-200)', 300: 'var(--color-admin-brand-300)', 400: 'var(--color-admin-brand-400)', 500: 'var(--color-admin-brand-500)', 600: 'var(--color-admin-brand-600)', 700: 'var(--color-admin-brand-700)', 800: 'var(--color-admin-brand-800)', 900: 'var(--color-admin-brand-900)', 950: 'var(--color-admin-brand-950)' },
        'admin-gray': { 25: 'var(--color-admin-gray-25)', 50: 'var(--color-admin-gray-50)', 100: 'var(--color-admin-gray-100)', 200: 'var(--color-admin-gray-200)', 300: 'var(--color-admin-gray-300)', 400: 'var(--color-admin-gray-400)', 500: 'var(--color-admin-gray-500)', 600: 'var(--color-admin-gray-600)', 700: 'var(--color-admin-gray-700)', 800: 'var(--color-admin-gray-800)', 900: 'var(--color-admin-gray-900)', 950: 'var(--color-admin-gray-950)', dark: 'var(--color-admin-gray-dark)' },
        'admin-success': { 25: 'var(--color-admin-success-25)', 50: 'var(--color-admin-success-50)', 200: 'var(--color-admin-success-200)', 500: 'var(--color-admin-success-500)', 600: 'var(--color-admin-success-600)', 950: 'var(--color-admin-success-950)' },
        'admin-error': { 25: 'var(--color-admin-error-25)', 50: 'var(--color-admin-error-50)', 200: 'var(--color-admin-error-200)', 500: 'var(--color-admin-error-500)', 600: 'var(--color-admin-error-600)', 950: 'var(--color-admin-error-950)' },
        'admin-warning': { 25: 'var(--color-admin-warning-25)', 50: 'var(--color-admin-warning-50)', 200: 'var(--color-admin-warning-200)', 500: 'var(--color-admin-warning-500)', 600: 'var(--color-admin-warning-600)', 950: 'var(--color-admin-warning-950)' },
      },
      fontFamily: { ui: 'var(--font-ui)', admin: 'var(--font-admin-ui)' },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '-0.02em' }],
        'headline-md': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'title-2xl': ['72px', { lineHeight: '90px', fontWeight: '700' }],
        'title-xl': ['60px', { lineHeight: '72px', fontWeight: '700' }],
        'title-lg': ['48px', { lineHeight: '60px', fontWeight: '700' }],
        'title-md': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'title-sm': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'theme-xl': ['20px', { lineHeight: '30px' }],
        'theme-sm': ['14px', { lineHeight: '20px' }],
        'theme-xs': ['12px', { lineHeight: '18px' }],
      },
      spacing: { 1: '4px', 2: '8px', 3: '12px', 4: '16px', 6: '24px', 8: '32px' },
      minHeight: { touch: 'var(--touch-target-min)', cta: 'var(--touch-target-cta)' },
      minWidth: { touch: 'var(--touch-target-min)' },
      boxShadow: { focus: '0 0 0 3px var(--focus-ring)' },
    },
  },
  plugins: [],
} satisfies Config
