export const PROBLEM_TYPES = {
  aboutBlank: 'about:blank',
  validation: 'https://pos.example/errors/validation',
  unauthorized: 'https://pos.example/errors/unauthorized',
  forbidden: 'https://pos.example/errors/forbidden',
  notFound: 'https://pos.example/errors/not-found',
  conflict: 'https://pos.example/errors/conflict',
  categoryHasProducts: 'https://pos.example/errors/category-has-products',
  categoryNameConflict: 'https://pos.example/errors/category-name-conflict',
  optionGroupInUse: 'https://pos.example/errors/option-group-in-use',
  optionInUse: 'https://pos.example/errors/option-in-use',
  optionGroupNameConflict:
    'https://pos.example/errors/option-group-name-conflict',
  productInUse: 'https://pos.example/errors/product-in-use',
  cloudinaryNotConfigured: 'https://pos.example/errors/cloudinary-not-configured',
  cloudinaryUploadFailed: 'https://pos.example/errors/cloudinary-upload-failed',
  alreadyVoided: 'https://pos.example/errors/already-voided',
  internal: 'https://pos.example/errors/internal',
  missingTenantContext: 'https://pos.example/errors/missing-tenant-context',
  invalidCredentials: 'https://pos.example/errors/invalid-credentials',
  csrfFailed: 'https://pos.example/errors/csrf-failed',
  sessionRevoked: 'https://pos.example/errors/session-revoked',
  sessionExpired: 'https://pos.example/errors/session-expired',
  rateLimited: 'https://pos.example/errors/rate-limited',
} as const;
